language: python
arch:
  - AMD64
  - ppc64le
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
#Power_jobs
    - python: 3.7
      dist: xenial
      sudo: true
      arch: ppc64le

install:
  - pip install -q nose
  - python setup.py install
Before_script:
  - |
     if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     https://github.com/nose-devs/nose/tarball/master#egg=nose-dev
     tar -xvf nose*
     export PATH=~/nose*/bin:$PATH
script:
  - nosetests -w /tmp blessings.tests
